# Generated by Django 5.0.6 on 2024-06-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html_version', models.CharField(max_length=10)),
                ('page_title', models.CharField(max_length=255)),
                ('num_headings', models.JSONField()),
                ('num_links', models.JSONField()),
                ('has_login_form', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
